In [1]:
import os
import numpy as np

5.19 Rotate a 2D Array

Image rotation is a fundamental operation in computer graphics. Figure 5.4 illustrates the rotation operation on a 2D array representing a bit-map of an image. Specifically, the image is rotated by 90 degrees clockwise.

Write a function that takes as input an n x n 2D array, and rotates the array by 90 degrees clockwise.
Hint: Focus on the boundary elements.

In [34]:
def rotate_90_clock_np(arr):
    arr = np.array(arr)
    arr_rot = np.zeros(arr.shape)
    for old_row_ind, new_col_ind in enumerate(range(len(arr))[::-1]):
        arr_rot[:, new_col_ind] = arr[old_row_ind, :]
    return arr_rot

def rotate_90_clock(arr):
    n = len(arr)
    arr_rot = [[None] * n for i in range(n)]
    for old_row_ind, new_col_ind in enumerate(range(n)[::-1]):
        for old_col_ind, new_row_ind in enumerate(range(n)):
            arr_rot[new_row_ind][new_col_ind] = arr[old_row_ind][old_col_ind]
    return arr_rot

# arr = [[i] * n for i in range(5)]
# arr = [[1, 2], [3, 4]]
arr = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

arr_rot = rotate_90_clock(arr)

print(np.array(arr))
print('')
print(np.array(arr_rot))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]


In [33]:
[[None] * n for i in range(n)]

[[None, None, None, None],
 [None, None, None, None],
 [None, None, None, None],
 [None, None, None, None]]